---
# tasks file for buildkite-agent

- name: Debian | Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: true
  when: ansible_distribution in debian_family_distros or ansible_distribution == 'ArchLinux'

- name: CentOS | Install nginx
  become: true
  yum:
    name: nginx
    state: present
    update_cache: true
  when: ansible_distribution in centos_family_distros