---
# handlers file for buildkite-agent
- name: reload systemd daemon
  systemd:
    daemon_reload: true

- name: restart buildkite-agent service
  service:
    name: buildkite-agent
    state: restarted
