---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: True

  tasks:
    - name: reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Gather the service facts
      ansible.builtin.service_facts:

    - name: Check if buildkite-agent system is present
      ansible.builtin.assert:
        that: "'buildkite-agent' in ansible_facts.services"
