---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: True
  tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Check if 'nginx' is installed
    ansible.builtin.assert:
      that: "'nginx' in ansible_facts.packages"